#!/bin/sh

cleanUp () {
    i3-msg '[class="Google-chrome"] kill'
    sleep 1
}

case "$1" in
    lock)
        i3lock -c 000000
        ;;
    logout)
        cleanUp
        i3-msg 'exit'
        ;;
    suspend)
        sudo pm-suspend | i3lock -c 000000
        ;;
    hibernate)
        sudo pm-hibernate
        ;;
    reboot)
        cleanUp
        sudo shutdown -r now
        ;;
    shutdown)
        cleanUp
        sudo shutdown -h now
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
